### ISSUE TITLE
Recursive list of files doesn't work

### ISSUE THREAD

**Issue by mparpaillon** [markmarijnissen/cordova-promise-fs#18]
Hi,

In the `list` function, the promise is resolved before the subdirectories are read. So you only return the files read in the root directory.

I've tried to fix it but I've never been a "promise genius" and I can't get it to work properly

See this issue: https://github.com/markmarijnissen/cordova-app-loader/issues/90

**Comment by markmarijnissen** [comment]
it should work again, yet with a limitation of max 100 entries
