### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by Gfast2** [markmarijnissen/cordova-promise-fs#22]
I'm try to use this wrapper library to build a simple logger system to log system status of the app into a file locally.
But I got `require is not defined` issue. If I just delete 'Promise: require('promiscuous')', I will work, but I've tried to log some thing into a created file. But when I try to read it immediately, it's just empty. By the `fs.deviceready` method, I just got `[object Promise]`. 
Any suggestion? Thanks! - Su

**Comment by SystemParadox** [comment]
`require` should be provided by your commonJS bundler (e.g. webpack or browserify).

**Comment by Gfast2** [comment]
Thanks!
