### ISSUE TITLE
Download fails on Android when url's contain '../' in it

### ISSUE THREAD

**Issue by starquake** [markmarijnissen/cordova-promise-fs#7]
Download fails on Android when url's contain '../' in it. I'm not entirely sure but IIRC this doesn't seem to be an issue on iOS.

I want to make a PR with a fix but I wanted to check with you if you agree with me that this should be fixed in the function 'normalize'.

Is it okay with you if I improve the function normalize so that it will return a normalized path?

Like this:
"http://10.10.1.104:9000/site//Mobile/../css/tinymce-content.css"
into
"http://10.10.1.104:9000/site/css/tinymce-content.css"

**Comment by starquake** [comment]
Mmmm I'm starting to think this actually might be a bug in 'cordova-plugin-file-transfer'

**Comment by markmarijnissen** [comment]
Would be wonderful if you enhance the normalize function! If you do, please submit a pull request and I'll try to merge within a week. (in the weekends)
